# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
    paths:
      - "v1"

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Build APK
        run: flutter build apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk

    #  - uses: actions/checkout@v3
    #    name: SonarQube Scan
    #  - uses: sonarsource/sonarqube-scan-action@master
      - name: Configure Proxy
        run: |
          echo "::set-env name=HTTP_PROXY::http://192.168.1.8:9000/"
          echo "::set-env name=HTTPS_PROXY::https://192.168.1.8:9000/"
      - name: Retry SonarScanner
        uses: softprops/action-retry@v1
        with:
          retries: 3 # Number of retries
          delay: 5000 # Delay in milliseconds between retries
        if: failure() # Retry only if the previous step failed
      - run: sonar-scanner -Dsonar.login=$SONAR_TOKEN

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload to Sauce Labs
        uses: saucelabs/saucectl-run-action@v3

      

