# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart
on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
    paths:
      - "v1"

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: dart analyze
      
      - name: Checkout Latest Commit
        uses: actions/checkout@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: sharecare-ngurram
          token: ${{ secrets.SONAR_TOKEN }}

    #  - uses: actions/checkout@v2
      - uses: stackhawk/hawkscan-action@v2.1.1
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}

   #   - name: Check deps
   #     uses: nnichols/clojure-vulnerability-check-action@v1

      - name: Build APK
        run: flutter build apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
             
   #   - name: Run Snyk Dependency Scan
   #     env:
   #       SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
   #     run: snyk test

      - name: Upload to Sauce Labs
        uses: saucelabs/saucectl-run-action@v3
