name: Sauce Labs Deployment

on:
  push:
    branches:
      - master  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust Node.js version as needed
      - uses: actions/checkout@v3
        
              # Note: This workflow uses the latest stable version of the Dart SDK.
              # You can specify other versions if desired, see documentation here:
              # https://github.com/dart-lang/setup-dart/blob/main/README.md
      - uses: dart-lang/setup-dart@v1
      - name: Set up Flutter 
        uses: subosito/flutter-action@v2
        with: 
            flutter-version: '3.10.6'
      - name: Install dependencies
        run: flutter pub get
              # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
                  name: app-release.apk
                  path: build/app/outputs/apk/release/app-release.apk
                  test_apk_path: 'build/app/outputs/apk/release/app-release.apk'
      - name: Saucectl RUN
        run: npm install -g saucectl
      - name: Deploy to Sauce Labs
        run: saucectl run
          # Replace with your deployment commands to Sauce Labs
          # For example:
          # saucectl run .sauce/config.yml --region us-west-1
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
