# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: iOS

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
    paths:
      - "v1"

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - name: Install dependencies
        run: flutter pub get

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          
      - uses: actions/checkout@v2
      - uses: stackhawk/hawkscan-action@v2.1.1
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
    

      - name: Install SonarScanner
        run: |
          brew install sonar-scanner
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Sharecare-NGurram_Sample-Flutter-App-main \
            -Dsonar.organization=sharecare-ngurram \
            -Dsonar.sources=./  # Adjust this path as needed
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - uses: actions/checkout@v2
      - uses: stackhawk/hawkscan-action@v2.1.2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}

      - name: Build iOS app without code signing
        run: flutter build ios --release --no-codesign


      - name: Archive iOS app without code signing
        run: flutter build ios --release --no-codesign

      - name: Package .app into .ipa
        run: |
          mkdir -p Payload
          cp -R build/ios/Release-iphoneos/Runner.app Payload/
          zip -r app.ipa Payload/

      - name: Publish .ipa as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-ipa
          path: app.ipa
          
 #     - name: Upload iOS build artifact
 #       uses: actions/upload-artifact@v3
 #       with:
 #         name: my-artifact
 #         path: build/
 #         name: ios.aab

      - name: List Workspace Contents After Upload
        run: |
          ls -R $GITHUB_WORKSPACE
          
      - name: Upload to Sauce Labs
        uses: saucelabs/saucectl-run-action@v3

