# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: iOS

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
    paths:
      - "v1"

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build iOS app without code signing
        run: flutter build ios --release --no-codesign
        
      - name: SonarCloud Scan
        run: |
          ./gradlew sonarqube \
           -Dsonar.projectKey=Sharecare-NGurram_Sample-Flutter-App-main \
           -Dsonar.organization=sharecare-ngurram \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


   #   - name: Install SonarScanner
   #     run: |
   #       curl -L -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-macosx.zip
   #       unzip sonar-scanner.zip
   #       export PATH="$PATH:$(pwd)/sonar-scanner-cli-5.0.1.3006-macosx/bin"

   #   - name: Run SonarCloud analysis
   #     env:
   #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   #     run: |
   #       sonar-scanner-cli-5.0.1.3006-macosx\sonar-scanner-5.0.1.3006-macosx\bin\sonar-scanner \
   #         -Dsonar.projectKey=Sharecare-NGurram_Sample-Flutter-App-main \
   #         -Dsonar.organization=sharecare-ngurram \
   #         -Dsonar.sources=src \
   #         -Dsonar.host.url=https://sonarcloud.io
   


      - name: Archive iOS app without code signing
        run: flutter build ios --release --no-codesign

      - name: Package .app into .ipa
        run: |
          mkdir -p Payload
          cp -R build/ios/Release-iphoneos/Runner.app Payload/
          zip -r app.ipa Payload/

      - name: Publish .ipa as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-ipa
          path: app.ipa
          
 #     - name: Upload iOS build artifact
 #       uses: actions/upload-artifact@v3
 #       with:
 #         name: my-artifact
 #         path: build/
 #         name: ios.aab

      - name: List Workspace Contents After Upload
        run: |
          ls -R $GITHUB_WORKSPACE
          
      - name: Upload to Sauce Labs
        uses: saucelabs/saucectl-run-action@v3

