# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: iOS

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
    paths:
      - "v1"

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build iOS app without code signing
        run: flutter build ios --release --no-codesign

      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli.zip
          export PATH="$PATH:$(pwd)/sonar-scanner-cli-4.6.2.2472-linux/bin"
          sonar-scanner

      - name: Scan with StackHawk
        env:
          STACKHAWK_API_KEY: ${{ secrets.STACKHAWK_API_KEY }}
        run: |
          curl -fsSL https://stackhawk.com/sh | bash -s scan --api-key $STACKHAWK_API_KEY

      - name: Archive iOS app without code signing
        run: flutter build ios --release --no-codesign

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios.ipa
          path: build/ios/
          
      - name: Upload to Sauce Labs
        uses: saucelabs/saucectl-run-action@v3

