apiVersion: v1alpha
kind: espresso
defaults: {}
showConsoleLog: false
sauce:
  region: eu-central-1
  concurrency: 10
espresso:
#  app: /Users/runner/work/Sample-Flutter-App-main/Sample-Flutter-App-main/build/ios/Release-iphoneos/Runner.app/Frameworks/libswiftFoundation.dylib
  app: /home/runner/work/Sample-Flutter-App-main/Sample-Flutter-App-main/build/app/outputs/ipa/release/ios.aab
  testApp: /home/runner/work/Sample-Flutter-App-main/Sample-Flutter-App-main/build/app/outputs/ipa/release/ios.aab
#  testApp: /Users/runner/work/Sample-Flutter-App-main/Sample-Flutter-App-main/build/ios/Release-iphoneos/Runner.app/Frameworks/libswiftFoundation.dylib
suites:
  - name: iOS Test Suite
    devices:
      - platformName: iOS
        platformVersion: 15.0
        deviceName: iPhone 12 Simulator
        appiumVersion: 1.21.0
        browserName: Safari
#- name: iPhone 14 Simulator
#  devices:
#  - name: iPhone 14 Simulator
#  emulators:
#  - name: iPhone 14 Simulator
#    platformVersions:
#    - "iOS 16.1"
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: artifacts
